- libs/ngxtension/.eslintrc.json
- libs/ngxtension/project.json
- libs/ngxtension/repeat/README.md
- libs/ngxtension/repeat/ng-package.json
- libs/ngxtension/repeat/src/index.ts
- libs/ngxtension/repeat/src/repeat.spec.ts
- libs/ngxtension/repeat/src/repeat.ts
- tsconfig.base.json
closes #14
This PR adds `Repeat` directive that extends `NgFor`. This directive allows consumers to iterate over a number of times instead of a list of items
```html
<p *ngFor="let i of [0, 1, 2]">{{ i }}</p>
<p *ngFor="let i; repeat 3">{{ i }}</p>
```
> feat(repeat): add Repeat directive

- libs/ngxtension/assert-injector/src/index.ts
- libs/ngxtension/computed-from/README.md
- libs/ngxtension/computed-from/ng-package.json
- libs/ngxtension/computed-from/src/computed-from.spec.ts
- libs/ngxtension/computed-from/src/computed-from.ts
- libs/ngxtension/computed-from/src/index.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
- libs/ngxtension/project.json
- pnpm-lock.yaml
- tsconfig.base.json
closes #2 
- added computedFrom utility fn (with ability to pass an injector)
- tests for multiple cases
> feat(computed-from): added computed from

- libs/ngxtension/assert-injector/src/assert-injector.ts
- libs/ngxtension/computed-from/src/computed-from.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
- libs/ngxtension/repeat/src/repeat.ts
- libs/ngxtension/resize/src/resize.ts
> docs: add jsdocs comments for all functions

- libs/ngxtension/computed-from/src/computed-from.spec.ts
- libs/ngxtension/inject-destroy/README.md
- libs/ngxtension/inject-destroy/ng-package.json
- libs/ngxtension/inject-destroy/src/index.ts
- libs/ngxtension/inject-destroy/src/inject-destroy.spec.ts
- libs/ngxtension/inject-destroy/src/inject-destroy.ts
- libs/ngxtension/project.json
- tsconfig.base.json
> feat: added inject-destroy

- CONTRIBUTING.md
- docs/astro.config.mjs
- docs/src/content/docs/utilities/call-apply.md
- libs/ngxtension/call-apply/README.md
- libs/ngxtension/call-apply/ng-package.json
- libs/ngxtension/call-apply/project.json
- libs/ngxtension/call-apply/src/call-apply.spec.ts
- libs/ngxtension/call-apply/src/call-apply.ts
- libs/ngxtension/call-apply/src/index.ts
- tsconfig.base.json
Hi I've implemented `CallPipe` and `ApplyPipe` + added some tests and docs (hope to make it in the right places)
@nartc I edited even the CONTRIBUTING.md just to fix a little typo for the nx command to create the secondary entry because I haven't the `pnx` command that you wrote, or maybe it's some kind of script/alias??
And added an short section about test (because I need even the nx command to run them 😉)  
Maybe another section to add is about where to put and how to write docs?
Closes #35
> feat(call-apply): Implemented call apply Pipes

- docs/src/content/docs/utilities/inject-destroy.md
> docs: inject-destroy

- docs/src/content/docs/utilities/connect.md
> docs: connect fn

- docs/src/content/docs/utilities/inject-destroy.md
- libs/ngxtension/inject-destroy/src/inject-destroy.spec.ts
- libs/ngxtension/inject-destroy/src/inject-destroy.ts
This PR augments the return type of `injectDestroy` to also include `onDestroy` so that folks don't have to `inject(DestroyRef)` when they need it to run arbitrary destroy logic using `DestroyRef#onDestroy`
> fix(inject-destroy): add onDestroy to return value of injectDestroy

- README.md
- docs/astro.config.mjs
add autogenerate to generate navigation sidebar. 
This way you just have to create your file and you do not forget to add it inside the conf.
What do you think?
> fix(navigation): use autogenerate fonction to create navigation sidebar

- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/intl/intl.component.ts
- docs/src/content/docs/utilities/connect.md
- docs/src/content/docs/utilities/intl.md
- libs/ngxtension/intl/README.md
- libs/ngxtension/intl/ng-package.json
- libs/ngxtension/intl/project.json
- libs/ngxtension/intl/src/display-names.pipe.ts
- libs/ngxtension/intl/src/display-names.spec.ts
- libs/ngxtension/intl/src/index.ts
- libs/ngxtension/intl/src/list-format.pipe.ts
- libs/ngxtension/intl/src/list-format.spec.ts
- libs/ngxtension/intl/src/plural-rules.pipe.ts
- libs/ngxtension/intl/src/plural-rules.spec.ts
- libs/ngxtension/intl/src/relative-time-format.pipe.ts
- libs/ngxtension/intl/src/relative-time-format.spec.ts
- libs/ngxtension/intl/src/supportedValuesOf.pipe.ts
- libs/ngxtension/intl/src/supportedValuesOf.spec.ts
- tsconfig.base.json
As we've talked, I'm pushing the new `Intl` pipes that I think could be useful.
These are:
* [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames) 
* [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat)
* [Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules)
* [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat)
* [Intl.supportedValuesOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf)
I've written some tests that cover all helpers.
Fixes #72
> Additional Intl API helpers

- libs/ngxtension/README.md
- libs/ngxtension/package.json
This commit will update the package page on npmjs
https://www.npmjs.com/package/ngxtension
Which is missing github & homepage links, and few more metadata fields.
> update ngxtension package.json and README.md

- docs/src/content/docs/utilities/host-binding.md
- libs/ngxtension/host-binding/README.md
- libs/ngxtension/host-binding/ng-package.json
- libs/ngxtension/host-binding/project.json
- libs/ngxtension/host-binding/src/host-binding.spec.ts
- libs/ngxtension/host-binding/src/host-binding.ts
- libs/ngxtension/host-binding/src/index.ts
- tsconfig.base.json
As the title of the pull request suggests I added a `hostBinding` function that can be used to bind properties like `@HostBinding` would, but to signals (either writable or readonly).
As you would do to properties bound with the decorator, you are still able to set/update/mutate the signal if it is writable.
> This is my very first OSS contribution, I hope I didn't mess up :sweat_smile:
> feat: add a signal base hostBinding function

- docs/src/content/docs/utilities/Injectors/assert-injector.md
- libs/ngxtension/assert-injector/src/assert-injector.spec.ts
- libs/ngxtension/assert-injector/src/assert-injector.ts
This PR adds an overload for `assertInjector` where it can accept a `runner` function. This overload shortens the userland code by not having the userland code to call `runInInjectionContext` explicitly.
> feat(assert-injector): add run mode for assertInjector

- docs/src/content/docs/utilities/Operators/map-skip-undefined.md
- libs/ngxtension/inject-is-intersecting/src/inject-is-intersecting.ts
- libs/ngxtension/map-skip-undefined/README.md
- libs/ngxtension/map-skip-undefined/ng-package.json
- libs/ngxtension/map-skip-undefined/project.json
- libs/ngxtension/map-skip-undefined/src/index.ts
- libs/ngxtension/map-skip-undefined/src/map-skip-undefined.spec.ts
- libs/ngxtension/map-skip-undefined/src/map-skip-undefined.ts
- libs/ngxtension/tsconfig.spec.json
- tsconfig.base.json
This PR substitute #101 to add `mapSkipUndefined` and `filterUndefined` instead of old `mapFilter` proposed in #34
I also added simplified tests using `toArray()` as suggested by @tomalaforge + docs for both operators.
Hope this can be accepted.
> feat(map-skip-undefined): add mapSkipUndefined + filterUndefined operator

- docs/src/content/docs/utilities/Injectors/inject-lazy.md
- libs/ngxtension/inject-lazy/README.md
- libs/ngxtension/inject-lazy/ng-package.json
- libs/ngxtension/inject-lazy/project.json
- libs/ngxtension/inject-lazy/src/index.ts
- libs/ngxtension/inject-lazy/src/inject-lazy-impl.ts
- libs/ngxtension/inject-lazy/src/inject-lazy.spec.ts
- libs/ngxtension/inject-lazy/src/inject-lazy.ts
- tsconfig.base.json
This is a new PR as I planned to close the previous one https://github.com/nartc/ngxtension-platform/pull/80
I implemented some stuff with the implementation from @JeanMeche. Also added a test using mockLazyProvider util.
The impl uses observables instead of promises and I changed the name to `injectLazy` instead of `lazyService`
cc @JeanMeche would like you to give it another round of review. 
closes #44
> feat: added inject-lazy

- docs/src/content/docs/utilities/Directives/repeat.md
When I added the `repeat` util to my code I was wondering if I still had to add a `TrackByFunction` as well - after checking the code I now know that it's not needed.
This change should clarify this for other users.
> docs: add trackBy hint to repeat util

- libs/ngxtension/host-binding/src/host-binding.spec.ts
- libs/ngxtension/host-binding/src/host-binding.ts
> (#130) fix(host-binding): handle the setting of a class without a property

- libs/ngxtension/README.md
Current link in README (https://ngxtension.netlify.app/utilities/assert-injector/) is an invalid URL. Changed it to point to homepage.
> docs: fix documentation link in README

- docs/src/content/docs/utilities/Directives/resize.mdx
the resize documentation had a wrong import link
> docs: fix link

- docs/src/content/docs/utilities/Signals/signal-slice.md
- libs/ngxtension/connect/src/connect.ts
- libs/ngxtension/signal-slice/README.md
- libs/ngxtension/signal-slice/ng-package.json
- libs/ngxtension/signal-slice/project.json
- libs/ngxtension/signal-slice/src/index.ts
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
- tsconfig.base.json
This was created in collaboration with Chau, it adds `signalSlice` which is loosely inspired by the `createSlice` API from Redux Toolkit. The general idea is that it allows you to declaratively create a "slice" of state. This state will be available as a readonly signal.
The key motivation, and what makes this declarative, is that all the ways for updating this signal are declared upfront with `sources` and `reducers`. It is not possible to imperatively update the state.
This PR also makes minor changes to `connect` in order to expose types that are shared by this utility.
Example using all API features:
```ts
state = signalSlice({
initialState: this.initialState,
sources: [this.sources$],
reducers: {
add: (state, checklist: AddChecklist) => ({
checklists: [...state.checklists, …
```
> feat(signal-slice): add signalSlice

- docs/src/content/docs/utilities/Signals/signal-slice.md
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
This adds an `effects` config to `signalSlice`. It uses the standard signal `effect` internally, this just allows you to define your effects within the `signalSlice` definition rather than having to define them separately in a `constructor` or field initialiser:
```ts
state = signalSlice({
initialState: this.initialState,
sources: [this.sources$],
reducers: {
add: (state, checklist: AddChecklist) => ({
checklists: [...state.checklists, this.addIdToChecklist(checklist)],
}),
},
effects: (state) => ({
init: () => {
console.log('hello');
},
saveChecklists: () => {
// side effect to save checklists
console.log(state.checklists());
},
}),
});
```
Note that I have added but disabled tests for this feature pending the ability to use `flushEffects`
> feat(signal-slice): add effects config

- docs/src/content/docs/utilities/Signals/signal-slice.md
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
This is a draft implementation that allows optionally supplying sources as a function that can utilise the current state and return an array of sources.
This addresses what I think is a fundamental problem with the current implementation and is highlighted by this use case from @justinrassier on Twitter: https://twitter.com/justinrassier/status/1722619039787446438 - I've also already run into this issue for error handling
Actions can be created by defining reducers, but if you want a source to be able to utilise an action you have to define one separately outside of `signalSlice` (e.g. as in the example above where a separate `load$` action is created with a subject).
This change would allow (optionally) supplying a function instead of an array of sources directly:
```ts
state = …
```
> feat(signal-slice): add asyncReducers

- docs/src/content/docs/utilities/Signals/signal-slice.md
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
This adds the ability to supply a source as a function that accepts the state signal - this allows a source to access the current state if necessary, e.g:
```ts
state = signalSlice({
initialState: this.initialState,
sources: [
this.loadChecklists$,
(state) =>
this.newMessage$.pipe(
map((newMessage) => ({
messages: [...state().messages, newMessage],
}))
),
],
});
```
> feat(signal-slice): allow supplying source as a function that accepts state signal

- docs/src/content/docs/404.md
In case user visits invalid URL, they should have a prominent way to go back to homepage.
Current behavior when opening not existing page:
After adding 404 page:
> feat: add 404 page

- docs/src/content/docs/utilities/Signals/computed-from.md
This PR fixes [Issue 159](https://github.com/nartc/ngxtension-platform/issues/159).
Updates the docs at "[computedFrom - Use it outside of an injection](https://ngxtension.netlify.app/utilities/signals/computed-from/#5-use-it-outside-of-an-injection-context)" with an example that reflects the real usage of the function.
> docs: fix computedFrom example with injector

- docs/src/content/docs/utilities/Signals/signal-slice.md
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
The rationale for this PR is covered in more detail in this issue: https://github.com/nartc/ngxtension-platform/issues/155
I think this greatly simplifies the API and makes explaining the mental model for how `signalSlice` updates state much more clear, e.g:
* `sources` - observables that are mapped to the state they want to update
* `actionSources` - actions that return sources
versus (old):
* `sources` - observables that are mapped to the state they want to update
* `reducers` - actions that return a reducer function to update state synchronously
* `asyncReducers` - actions that return sources to update state asynchronously
> refactor(signal-slice): remove reducers, rename asyncReducers to actionSources

- .all-contributorsrc
- .prettierrc
- libs/ngxtension/to-lazy-signal/README.md
- libs/ngxtension/to-lazy-signal/ng-package.json
- libs/ngxtension/to-lazy-signal/project.json
- libs/ngxtension/to-lazy-signal/src/index.ts
- libs/ngxtension/to-lazy-signal/src/to-lazy-signal.spec.ts
- libs/ngxtension/to-lazy-signal/src/to-lazy-signal.ts
- tsconfig.base.json
Function `toLazySignal()` is a proxy function that will call the original `toSignal()` function when the returned signal is read for the first time.
[Demo](https://stackblitz.com/edit/stackblitz-starters-wxbnsh?devToolsHeight=33&file=src%2Fmain.ts)
> feat: add toLazySignal()

- docs/src/content/docs/utilities/Signals/to-lazy-signal.md
Add toLazySignal() documentation to the docs (Signals).
> docs: add toLazySignal() documentation

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
Fixes an issue where if a Subject with a union type e.g `Subject<number | null>` was supplied as an `actionSource` the resulting typing for its action method would be incorrectly inferred as `number & Observable<null>`
Credit goes to @nartc for this one, all I did was nerd snipe him on Twitter
> fix(signal-slice): typing for Subject action source with union type

- docs/src/components/Content.astro
- docs/src/components/Contributor.astro
- docs/src/content/config.ts
- docs/src/content/contributors/thomas-laforge.json
- docs/src/content/docs/utilities/Operators/filter-array.md
- docs/src/content/docs/utilities/Operators/filter-nil.md
- docs/src/content/docs/utilities/Operators/map-array.md
To follow up on the contributor button and from the idea of @ajitzero, I added a new collection to collect contributors data where we can add a link to twitter, github, linkedin. Other link can be added.
> feat: add collection for contributors

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
Optional properties in the initial state pose an issue with selectors, this PR forces a user to set it as undefined instead.
Issue explaining in detail: https://github.com/nartc/ngxtension-platform/issues/176
> fix(signal-slice): Do not allow optional properties in signalSlice

- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/document-visibility-state/document-visibility-state.component.ts
- docs/src/content/docs/utilities/Injectors/document-visibility-state.md
- libs/ngxtension/document-visibility-state/README.md
- libs/ngxtension/document-visibility-state/ng-package.json
- libs/ngxtension/document-visibility-state/project.json
- libs/ngxtension/document-visibility-state/src/document-visibility-state.spec.ts
- libs/ngxtension/document-visibility-state/src/document-visibility-state.ts
- libs/ngxtension/document-visibility-state/src/index.ts
- tsconfig.base.json
Ported https://vueuse.org/core/useDocumentVisibility/ to Angular.
> feat: added injectDocumentVisibility utility

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
EDIT: The implementation of this has changed quite a bit since I did it initially so I've updated this comment to reflect that.
There might still be a bit of tweaking to do here (I haven't been able to properly type action.payload but all the other properties are fine), and I will need to write some docs, but it's at a state where it would be great to get some feedback. It works as is, I'm just not 100% sure on the API.
The initial motivation for this was an example from @nartc attempting to implement Real World app and running into an issue where an `actionSource` would need to run and once that completed a side effect (navigation) would need to occur with a dynamic route.
Currently with signalSlice, the primary way to execute effects is by reacting to a state change, but it seems useful …
> feat(signal-slice): add actionEffects config

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
Changed the selector definition to be the entire signalSlice as oposed to just the state.
Not sure how to run the tests (the docs just say to 'run the tests'), so not sure if this also required a change to the test framework. The changed version did do what I'd expect in my project.
> Pass the entire slice to selectors function

- docs/astro.config.mjs
- docs/src/content/docs/es/getting-started/installation.mdx
- docs/src/content/docs/es/getting-started/introduction.md
- docs/src/content/docs/es/index.mdx
- docs/src/content/docs/es/utilities/Components/host-binding.md
- docs/src/content/docs/es/utilities/Directives/click-outside.md
- docs/src/content/docs/es/utilities/Directives/repeat.md
- docs/src/content/docs/es/utilities/Directives/resize.mdx
- docs/src/content/docs/es/utilities/Directives/trackby-id-prop.md
- docs/src/content/docs/es/utilities/Forms/if-validator.md
- docs/src/content/docs/es/utilities/Gesture/gesture.mdx
- docs/src/content/docs/es/utilities/Gesture/intro.md
- docs/src/content/docs/es/utilities/Miscellaneous/singleton-proxy.md
- Adds internationalization to docs
- Adds translation in Spanish to the  landing page and the pages in the following folders:
1. Getting Started
2. Components pages
3. Directives 
4. Forms
5. Gesture
6. Miscellaneous
Addresses https://github.com/nartc/ngxtension-platform/issues/150
> feat(docs): add internationalization to docs

- libs/ngxtension/connect/src/connect.ts
- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
EDIT: The note below has been resolved
NOTE: This is a draft PR due to one remaining issue and I'm not sure if it can be solved with this set up. I think the crux of the issue is that I am relying on a proxy to detect when the state object is accessed in order to trigger the `lazySources` to `connect`:
```ts
return new Proxy(slice, {
get(target, property, receiver) {
if (!lazySourcesLoaded) {
lazySourcesLoaded = true;
connectSources(state, lazySources, injector);
}
return Reflect.get(target, property, receiver);
},
});
```
Although it still seems to work (the observable values are still set into the signal), it triggers the `SIGNAL_WRITE_FROM_ILLEGAL_CONTEXT` error:
```
ERROR Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use …
```
> feat(signal-slice): add lazySources

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
Fixes the issues discussed here: https://github.com/nartc/ngxtension-platform/issues/196 where lazySources were not being connected if the state signal value was accessed directly.
P.S. not sure what is happening with the formatting/trailing commas, let me know if I need to fix something here
> fix(signal-slice): add apply trap to proxy for loading lazySources when signal value accessed directly

- docs/src/content/docs/utilities/Signals/computed-from.md
The `options`-object is currently inside the `pipe`. This moves it to be the 3rd argument of the `computedFrom`-function.
> docs: third arg is the options-obj for computedFrom

- docs/src/content/docs/es/utilities/Forms/control-error.md
- docs/src/content/docs/utilities/Forms/control-error.md
- libs/ngxtension/control-error/src/control-error.ts
Improve configuration section in docs
reduce emits of NGX_DEFAULT_CONTROL_ERROR_STATE_MATCHER
share statematcher computation in  NgxControlError
> refactor(NgxControlError): improve statematcher

- libs/ngxtension/create-injection-token/src/create-injection-token.spec.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
This adds a `createService` abstraction for `createInjectionToken`. The primary purpose is to make the API more appealing for the role of creating a service using `createInjectionToken` and is mostly cosmetic. However, `createService` currently does not allow using the `multi` option as this does not make sense for services, and it will also require that the factory function returns an object.
> feat(create-injection-token): add createService

- libs/ngxtension/connect/src/connect.spec.ts
- libs/ngxtension/connect/src/connect.ts
Ignore `null` and `undefined` values of signal before performing `typeof object` comparison for spread operator
Fixes #157
> fix(connect): handle null when performing typeof object

- docs/src/content/docs/es/utilities/Assets/svg-sprites.md
- docs/src/content/docs/utilities/Assets/svg-sprites.md
- libs/ngxtension/svg-sprite/src/svg-sprite.ts
`createSvgSprite` is an internal method, which gets called by provideSvgSprites. So remove it from the docs.
@nartc Please have a look at this quick fix of the docs!
Cheers 😃
> docs(NgxSvgSprite): align provideSvgSprites sections with implementation

- docs/src/content/docs/utilities/Signals/computed-async.md
- libs/ngxtension/computed-async/README.md
- libs/ngxtension/computed-async/ng-package.json
- libs/ngxtension/computed-async/project.json
- libs/ngxtension/computed-async/src/computed-async.spec.ts
- libs/ngxtension/computed-async/src/computed-async.ts
- libs/ngxtension/computed-async/src/index.ts
- libs/ngxtension/package.json
- tsconfig.base.json
Closes https://github.com/nartc/ngxtension-platform/issues/228 
Can be used as: 
```ts
private http = inject(HttpClient);
productId = injectQueryParams('productId');
product = computedAsync(() => {
const productId = this.productId();
if (!productId) return null;
return this.http.get<{ id: string; title: string }>(`${API}/${productId}`)
});
```
> Uses `switchMap` to cancel ongoing requests. 
Playground: [https://stackblitz.com/edit/stackblitz-starters-pzxg8a?file=src%2Fcomputed-async.ts,src%2Fmain.ts,src%2Fglobal_styles.css](https://stackblitz.com/edit/stackblitz-starters-pzxg8a?file=src%2Fcomputed-async.ts,src%2Fmain.ts,src%2Fglobal_styles.css)
> feat: added computed-async impl

- docs/src/content/docs/utilities/Signals/to-observable-signal.md
- libs/ngxtension/to-observable-signal/README.md
- libs/ngxtension/to-observable-signal/ng-package.json
- libs/ngxtension/to-observable-signal/project.json
- libs/ngxtension/to-observable-signal/src/index.ts
- libs/ngxtension/to-observable-signal/src/to-observable-signal.spec.ts
- libs/ngxtension/to-observable-signal/src/to-observable-signal.ts
- tsconfig.base.json
`toObservableSignal()` combines the functionality of Angular Signal and RxJS Observable.
https://stackblitz.com/edit/stackblitz-starters-owzm3q?file=src%2Fmain.ts
```ts
@Component({
selector: 'my-app',
standalone: true,
imports: [CommonModule],
template: `
<h2>Signal A: {{ a() }}</h2>
<h2>Observable A: {{ a | async }}</h2>
<h2>Observable B (A*2): {{ b | async }}</h2>
<h2>Signal C (A*3): {{ c() }}</h2>
`,
})
export class App {
a = toObservableSignal(signal<number>(0));
b = this.a.pipe(
switchMap((v) => {
return of(v * 2);
}),
);
c = computed(() => this.a() * 3);
constructor() {
setInterval(() => this.a.set(1), 10000);
setInterval(() => this.a.update((v) => v + 1), 1000);
}
}
```
> feat: add toObservableSignal()

- libs/ngxtension/to-observable-signal/src/index.ts
I made a stupid mistake and forgot to export in index.ts
> fix: correct export for toObservableSignal feature

- libs/ngxtension/connect/src/connect.spec.ts
- libs/ngxtension/connect/src/connect.ts
This fixes an issue where the signal would not be updated correctly when a non-literal object value is used to update a literal object value.
For example, attempting to update `{}` with `null` would result in the value still being `{}`
> fix(connect): update literal object values correctly for non-literal object values

- libs/ngxtension/package.json
Add ts-morph as a dependency, which is needed for the Signals Input migrator.
> fix: add dependency ts-morph for Signals Input migrator

- docs/src/content/docs/utilities/Injectors/create-injectable.md
- libs/ngxtension/create-injectable/README.md
- libs/ngxtension/create-injectable/ng-package.json
- libs/ngxtension/create-injectable/project.json
- libs/ngxtension/create-injectable/src/create-injectable.spec.ts
- libs/ngxtension/create-injectable/src/create-injectable.ts
- libs/ngxtension/create-injectable/src/index.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.spec.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
- tsconfig.base.json
Discussion: https://twitter.com/spierala/status/1748639069171568771
This PR removes the undocumented `createService` function added to the `create-injection-token` entry point in favour of:
1) Moving it to its own entry point
2) Renaming it to `createInjectable`
3) Having it return injectable directly instead of the injectFn/provideFn/token tuple that `createInjectionToken` returns by default
I've marked this as experimental for now to give us some flexibility in potential changes
EDIT: Updated usage based on updates from @nartc 
```ts
// defining a service
export const MyService = createInjectable(() => {
const myState = signal(1);
return { myState: myState.asReadonly() };
});
```
```ts
// provide the service
{
providers: [MyService];
}
```
```ts
// using the service
const myService = …
```
> feat(create-injectable): add createInjectable (replaces createService)

- docs/src/content/docs/utilities/Signals/signal-slice.md
Until TypeScript 5.4 is released (which will hopefully help address the issue of inferring types too early) both `effects` and `actionEffects` need to be supplied after other configurations otherwise the typing will be messed up. This adds a note to the docs about that.
closes #235
> docs(signal-slice): add note about effect ordering

- libs/ngxtension/computed-async/src/computed-async.spec.ts
- libs/ngxtension/computed-async/src/computed-async.ts
> fix(computedAsync): typings should return a union of undefined when no initial value.

- docs/src/content/docs/utilities/Stores/create-effect.md
- libs/ngxtension/create-effect/src/create-effect.spec.ts
- libs/ngxtension/create-effect/src/create-effect.ts
* Function, returned by `createEffect()` now accepts `Signal<T> | WritableSignal<T>` as an argument;
* `createEffect()` now has optional configuration argument of type `CreateEffectOptions`. Here you can pass an injector, configure if function should retry on error (true by default), and pass `retry()` configuration options. All fields are optional.
* Documentation of `createEffect()` is updated to reflect the changes.
BREAKING CHANGE: second argument, `injector`, is replaced by an object with fields `injector` and `retryOnError`.
> refactor: createEffect() !

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
I used the signal inputs generator on a big project recently and ran into trouble with cases like this:
```
<test [normalInput]="normalInput" />
<test-normalInput />
<normalInput />
<another-component something="blah-normalInput" />
```
In cases where:
* A child component input had the same name as a parent component input
* The name of an input was used as part of a tag name
* The name of an input was used within a property value
The template was being updated incorrectly, e.g:
```
<test [normalInput()]="normalInput()" />
<test-normalInput() />
<normalInput() />
<another-component something="blah-normalInput()" />
```
**NOTE:** I noticed there where two different regexes being used for the template based on whether it was a templateUrl or inline. One was simpler and I assume was …
> fix(convert-signal-inputs): handle input name overlap in template

- libs/ngxtension/connect/src/connect.spec.ts
- libs/ngxtension/connect/src/connect.ts
This PR proposes two changes:
* Allow supplying a signal to `.with` as well as to `connect` directly
* Allow for partial state updates with an origin signal
The primary use case I am aiming to support here is this (essentially allowing signals driven changes as well as observables):
```ts
// sources
private dogs = computedAsync(() => {
this.someService.version(); // retrigger when version changes
return this.dbService.getDogs();
});
private cats = computedAsync(() => {
this.someService.version();
return this.dbService.getCats();
});
// centralised state
private state = signal({
dogs: undefined,
cats: undefined,
})
constructor() {
// reducers
connect(this.state)
.with(() => ({ dogs: this.dogs() }))
.with(() => ({ cats: this.cats() }));
}
```
The current behaviour with origin signals does …
> feat(connect): allow updating partial values with signal through ConnectedSignal

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
Modifies regex so that if a property is accessed in the template that has the same name as some other input it won't be converted
closes #278
> fix(convert-signal-inputs): don't convert when input name used as property

- docs/src/content/docs/utilities/Signals/create-notifier.md
- libs/ngxtension/create-notifier/README.md
- libs/ngxtension/create-notifier/ng-package.json
- libs/ngxtension/create-notifier/project.json
- libs/ngxtension/create-notifier/src/create-notifier.spec.ts
- libs/ngxtension/create-notifier/src/create-notifier.ts
- libs/ngxtension/create-notifier/src/index.ts
- tsconfig.base.json
This is an initial implementation for the `createNotifier` feature discussed here: https://github.com/nartc/ngxtension-platform/issues/276
This incorporates some of the feedback in the discussion and we can continue to iterate on the exact API (personally I am happy with it as is but happy to change as well)
Once the exact implementation is settled I will add some docs to this PR (along with some more tests too)
> feat(create-notifier): add createNotifier

- docs/src/content/docs/utilities/Signals/signal-slice.md
closes #292 
Adds documentation for experimental `actionEffects`
> docs(signal-slice): add docs for experimental actionEffects

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
fixes #290 
Due to Automatic Semicolon Insertion this is valid JS/TS syntax:
```ts
@Component({})
export class MyCmp {
@Input() inputWithoutType;
noColon = true
}
```
But when processing property declarations this can mess with ts-morph since ASI has not been applied. This PR catches errors arising from this situation and warns to attempt fixing it and trying again.
> fix(convert-signal-inputs): handle automatic semicolon insertion issues

- libs/ngxtension/to-observable-signal/src/to-observable-signal.spec.ts
- libs/ngxtension/to-observable-signal/src/to-observable-signal.ts
This change removes a bit dirty method of combining the functionality of Angular Signal and RxJS Observable.
Previously, every field of Observable instance was copied to a Signal object.
Now we return a Proxy object, that only returns a method of the Observable instance if the Signal instance does not have the requested method.
> refactor: use Proxy in toObservableSignal() instead of methods linking, to be compatible with RxJS v8

- docs/src/content/docs/utilities/Migrations/new-outputs-migration.md
- libs/plugin/generators.json
- libs/plugin/src/generators/convert-outputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-outputs/compat.ts
- libs/plugin/src/generators/convert-outputs/generator.spec.ts
- libs/plugin/src/generators/convert-outputs/generator.ts
- libs/plugin/src/generators/convert-outputs/schema.d.ts
- libs/plugin/src/generators/convert-outputs/schema.json
Added migration support for: 
- EventEmitters -> output
- Observable/Subject/BehaviorSubject -> outputFromObservable
+ support for aliases 
+ docs
> feat(convert-outputs): add migrations for new output() function

- docs/src/components/Contributors.astro
- docs/src/content/config.ts
Before:
After:
Also add the missing website property to the contributors collection.
Feel free to dismiss :)
> docs: contributor badges fixes

- docs/src/content/docs/utilities/Injectors/inject-route-fragment.md
- libs/ngxtension/inject-route-fragment/README.md
- libs/ngxtension/inject-route-fragment/ng-package.json
- libs/ngxtension/inject-route-fragment/project.json
- libs/ngxtension/inject-route-fragment/src/index.ts
- libs/ngxtension/inject-route-fragment/src/inject-route-fragment.spec.ts
- libs/ngxtension/inject-route-fragment/src/inject-route-fragment.ts
- tsconfig.base.json
PR adds a injectRouteFragment() injector.
```ts
@Component()
class TestComponent implements OnInit {
injector = inject(Injector);
fragment: Signal<string | null> = injectRouteFragment();
ngOnInit() {
const isFragmentAvailable: Signal<boolean> = injectRouteFragment({
transform: (fragment) => !!fragment,
injector: this.injector,
});
}
}
```
> feat(inject-route-fragment): implementation of injectRouteFragment

- libs/plugin/src/generators/convert-outputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-outputs/generator.spec.ts
- libs/plugin/src/generators/convert-outputs/generator.ts
```typescript
@Output() someOutput: EventEmitter<DataInterface> = new EventEmitter();
// currently
someOutput = output();
// should be
someOutput = output<DataInterface>();
```
Closes https://github.com/nartc/ngxtension-platform/issues/312
> feat(output-migration): enhancements

- libs/plugin/migrations.json
This needs to be merged and released in a patch.
> fix: ng update wasn't working because of broken path

- libs/plugin/src/generators/convert-di-to-inject/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-di-to-inject/generator.spec.ts
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
Closes https://github.com/ngxtension/ngxtension-platform/issues/350
> fix: inject migration should take into account missing types for tokens

- libs/ngxtension/create-injectable/src/create-injectable.spec.ts
- libs/ngxtension/create-injectable/src/create-injectable.ts
If the factory function for `createInjectable` returns a proxy not all of the objects properties would be properly copied over with just `Object.assign`
> fix(create-injectable): allow returning proxies from factory function

- libs/plugin/src/generators/convert-outputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-outputs/generator.spec.ts
- libs/plugin/src/generators/convert-outputs/generator.ts
- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
Remove additional semicolumns created by the input generator.
I might be missing something because it seems like this is desired (#290), but I cannot think of/create an invalid example.
If accepted, I'll also update the output generator as this has the same issue.
Also sorry for not creating an issue first 😅 - I can still do this.
> fix(plugin): remove additional semicolumns

- libs/plugin/src/generators/convert-outputs/generator.ts
- libs/plugin/src/generators/convert-queries/generator.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
Issue encountered when attempting to execute migration scripts in the project after updating to Angular version 18. The migration scripts rely on the output() function, which is only available in Angular versions 17.3 and later. As a result, attempting to run these scripts on Angular 18 results in the following error:
`[ngxtension] output() is only available in v17.3 and later
`
> fix(migrations): Update Migration Scripts for Angular 18 Compatibility

- docs/src/content/contributors/jeanmeche.json
- docs/src/content/docs/utilities/Signals/explicit-effect.md
- libs/ngxtension/explicit-effect/README.md
- libs/ngxtension/explicit-effect/ng-package.json
- libs/ngxtension/explicit-effect/project.json
- libs/ngxtension/explicit-effect/src/explicit-effect.spec.ts
- libs/ngxtension/explicit-effect/src/explicit-effect.ts
- libs/ngxtension/explicit-effect/src/index.ts
Build on top of `effect()`, this helper function allows to only watch the producers passed as dependencies.
The effect itself is run as untracked preventing any hidden side effects.
> feat: add explicitEffect helper function.

- docs/src/content/docs/utilities/Migrations/inject-migration.md
- libs/plugin/src/generators/convert-di-to-inject/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-di-to-inject/generator.spec.ts
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.d.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.json
> feat(inject-migration): add option for ES private field support 

- docs/src/content/docs/index.mdx
We waited for the function to be released to add it to the homepage
> docs: add `explicitEffect` to the homepage

- libs/plugin/src/generators/convert-di-to-inject/generator.spec.ts
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.d.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.json
For the "inject-di-migration", a new option "useESPrivateFieldNotation" was added to support replacing TS "private" properties with ES private field properties.
However, an issue is found when executing the generator with the newly added option, and it's because of the option's name, "useESPrivateFieldNotation".
When running the schematic in a plain Angular app, i.e through Angular CLI with the "--help" option to get more insights about the schematic itself, we get the following:
Listed as the last one, besides the alias name provided in **schema json** , ngCLI also generates another, default alias: dash-separated name ( **--use-esprivate-field-notation** ).
Till now it's ok. but when we execute the schematic to do the work it's intended to and check the **options** at runtime, you can …
> fix(inject-migration): ng CLI option name problem

- docs/src/content/docs/es/utilities/Gesture/intro.md
- docs/src/content/docs/utilities/Gesture/intro.md
- docs/src/content/docs/utilities/Signals/merge-from.md
This PR addresses:
- The `mergeFrom` used a relative link that didn't work, so I made it absolute to the utilities like other links.
- The Gesture intro page linked to the Angular CDK on a now dead page, so I pointed it at the CDK in the Material docs.
The `resize` pages in both ES/EN say
- "injectResize retorna un Observable<ResizeResult> (see [ResizeResult TBD](http://127.0.0.1:4321/es/utilities/directives/resize/))"
I assume this is a dead end placeholder?
> Fix 404 on Gesture/intro and `mergeFrom` documentation

- docs/src/content/docs/es/index.mdx
- docs/src/content/docs/logos/logos.md
This is two similar but separate things
- The Press Kit images were 404'ing while deployed. However, for some reason they resolved fine when ran locally. WSL magic, caching, not sure. Anyways, they are now pointed to work locally and also I would assume as deployed.
- The Spanish main page was still pointing at the old logo.
> Fix: new logo paths

- docs/src/content/docs/index.mdx
- docs/src/content/docs/logos/logos.md
closes #411 
I believe the broken links came from the addition of `public` to the URL path.  
I built the docs with the updated links and on `preview`, the images were displayed.  
Sidenote: Github Codespaces has an older `pnpm` version installed so I downleveled to that versus updating `pnpm`.  I would think this shouldn't be problem in the near future.
> fix: Press Kit links

- libs/plugin/src/generators/shared-utils/migrate-signals-in-template.ts
Without this change the text contained in `value` will be shorter than `end - start` if it contains `\r\n`, since all the `\r` characters will be stripped out. This causes the change offset to be wrong for all subsequent changes.
> fix(signal-input-migration): preserve line endings

- docs/src/content/docs/index.mdx
- docs/src/content/docs/utilities/Migrations/sfc-migration.md
- libs/ngxtension/.eslintrc.json
- libs/plugin/generators.json
- libs/plugin/src/generators/convert-to-sfc/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-to-sfc/compat.ts
- libs/plugin/src/generators/convert-to-sfc/generator.spec.ts
- libs/plugin/src/generators/convert-to-sfc/generator.ts
- libs/plugin/src/generators/convert-to-sfc/schema.d.ts
- libs/plugin/src/generators/convert-to-sfc/schema.json
Closes https://github.com/ngxtension/ngxtension-platform/issues/362
> feat: add migration for sfc components

- docs/src/content/docs/utilities/Injectors/inject-local-storage.md
Docs build fails on `docs → utilities/Injectors/inject-local-storage.md frontmatter does not match collection schema.`
```
InvalidContentEntryFrontmatterError: **docs → utilities/Injectors/inject-local-storage.md** frontmatter does not match collection schema.
**title**: Required
at getEntryData (file:///Users/jmeinlschmidt/projects/ngxtension-platform/docs/node_modules/.pnpm/astro@4.7.0/node_modules/astro/dist/content/utils.js:86:26)
at async getContentEntryModule (file:///Users/jmeinlschmidt/projects/ngxtension-platform/docs/node_modules/.pnpm/astro@4.7.0/node_modules/astro/dist/content/vite-plugin-content-imports.js:164:35)
at async TransformContext.transform (file:///Users/jmeinlschmidt/projects/ngxtension-platform/docs/node_modules/.pnpm/astro@4.7.0/node_modules/astro/dist/content/vit …
```
> docs(inject-local-storage): Content entry frontmatter does not match schema

- docs/src/content/docs/es/getting-started/introduction.md
- docs/src/content/docs/es/utilities/Assets/svg-sprites.md
- docs/src/content/docs/es/utilities/Directives/repeat.md
- docs/src/content/docs/es/utilities/Directives/resize.mdx
- docs/src/content/docs/es/utilities/Forms/control-value-accessor.md
- docs/src/content/docs/es/utilities/Injectors/assert-injector.md
- docs/src/content/docs/es/utilities/Injectors/create-injection-token.md
- docs/src/content/docs/es/utilities/Intl/intl.md
- docs/src/content/docs/getting-started/introduction.md
- docs/src/content/docs/utilities/Assets/svg-sprites.md
- docs/src/content/docs/utilities/Directives/repeat.mdx
- docs/src/content/docs/utilities/Directives/resize.mdx
- docs/src/content/docs/utilities/Forms/control-value-accessor.md
- docs/src/content/docs/utilities/Injectors/assert-injector.md
- docs/src/content/docs/utilities/Injectors/create-injection-token.md
- docs/src/content/docs/utilities/Intl/intl.md
- docs/src/content/docs/utilities/Pipes/repeat.mdx
- libs/ngxtension/README.md
- libs/ngxtension/control-value-accessor/src/control-value-accessor.ts
- libs/ngxtension/svg-sprite/src/svg-sprite.ts
Migrated links `angular.io` to according pages in the new `angular.dev` website
> docs: Migrate links to angular.dev

- docs/src/content/docs/utilities/Injectors/inject-local-storage.md
- libs/ngxtension/inject-local-storage/src/inject-local-storage.spec.ts
- libs/ngxtension/inject-local-storage/src/inject-local-storage.ts
Link to the issue: [#506](https://github.com/ngxtension/ngxtension-platform/issues/506)
This is my first contribution to an Open Source project—the issue was labeled as a "Good First Issue."
This implementation aims to allow the compiler to differentiate between the provided arguments, ensuring that the correct code block is returned with the appropriate type. I used function overloading to handle different implementations.
My main concern is the interpretation of defaultValue. While it could be used as fallback data for initialValue, the issue is that we also listen for storage events, which might return an undefined value. I'm also unsure about the naming conventions.
I'm grateful for every remark and comment.
> feat: handle defaultValue not undefined typing

- docs/src/content/docs/utilities/Operators/derive-loading.md
Corrects `deriveLoading` entryPoint in docs, that wasn't replaced during previous entryPoint migration.
> fix(docs): fix incorrect derive loading entrypoint

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
Implementation of proposal discussed here: https://github.com/ngxtension/ngxtension-platform/issues/485
This PR is **non-breaking**, it adds onto the `state` object passed to sources but it does not change existing functionality
This adds the ability to use streams of the signal slices own state within sources (e.g. if there is an initial state property of `myVal` then a `myVal$` stream will be available on the state object passed to a source), which allows a `signalSlice` to react to its own state changing without needing to use external subjects, or without using an `actionSource` which will lead to a more imperative style of code.
Here is an example of plain RxJS handling a pagination scenario in a way that is cleanly declarative (but perhaps not the most practical):
```ts
pageNumber$ …
```
> feat(signal-slice): pass initial state streams to source functions

- libs/plugin/src/generators/convert-outputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-outputs/generator.spec.ts
- libs/plugin/src/generators/convert-outputs/generator.ts
Previously, this script would fail with a cryptic message (`cannot read property of undefined (reading includes)`) for input like:
```ts
@Output() myOutput: EventEmitter<string>;
```
The changes support that use case and:
- Uses the initialization in the constructor to infer the type (and removes it)
- Creates an initialization (`= output()`) if it doesn't exist
> fix(plugin): support outputs without inline initialization

- libs/ngxtension/signal-slice/src/signal-slice.spec.ts
- libs/ngxtension/signal-slice/src/signal-slice.ts
> fix(signal-slice): add initial state stream typing to state object

- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-array.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-basic.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-booleans.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-insideObject.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-number.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param-object.component.ts
- apps/test-app/src/app/linked-query-param/linked-query-param.component.ts
- apps/test-app/src/app/linked-query-param/routes.ts
- docs/src/content/docs/utilities/Injectors/linked-query-param.md
- libs/ngxtension/create-notifier/src/create-notifier.ts
- libs/ngxtension/linked-query-param/README.md
- libs/ngxtension/linked-query-param/ng-package.json
- libs/ngxtension/linked-query-param/project.json
- libs/ngxtension/linked-query-param/src/index.ts
- libs/ngxtension/linked-query-param/src/linked-query-param.spec.ts
- libs/ngxtension/linked-query-param/src/linked-query-param.ts
- tsconfig.base.json
Added docs for most of the usecases:
- string
- number
- boolean
- object
- array
Added example for filtering and pagination with resource API. 
Added multiple tests to test all the possible usecases.
Added 2 helper functions for easier parsing (paramToNumber, paramToBoolean), with support for defaultValue. 
Here is some self-explanatory code examples: 
```ts
export class MyCmp {
readonly searchQuery = linkedQueryParam('searchQuery');
// Parse a boolean query parameter
showHidden = linkedQueryParam('showHidden', { parse: paramToBoolean({defaultValue: false}) });
// Parse a number query parameter
count = linkedQueryParam('count', { parse: paramToNumber({defaultValue: 0}) });
// Parse an object query parameter
filter = linkedQueryParam('filter', {
parse: (value) => JSON.parse(value ?? …
```
> feat: add linkedQueryParam implementation, tests and docs

- libs/ngxtension/control-value-accessor/src/control-value-accessor.spec.ts
- libs/ngxtension/control-value-accessor/src/control-value-accessor.ts
> fix(ngx-control-value-accessor): accessing properties is outside of a reactive context

- docs/src/content/docs/utilities/Stores/create-effect.md
Fixes a typo in the `retryOnError` field in docs.
> fix(docs): fix typo in retryOnError field

- docs/src/content/docs/es/utilities/Injectors/inject-route-fragment.md
- docs/src/content/docs/utilities/Injectors/inject-params.md
- docs/src/content/docs/utilities/Injectors/inject-query-params.md
- docs/src/content/docs/utilities/Injectors/inject-route-data.md
- docs/src/content/docs/utilities/Injectors/inject-route-fragment.md
- libs/ngxtension/inject-params/src/inject-params.spec.ts
- libs/ngxtension/inject-params/src/inject-params.ts
- libs/ngxtension/inject-query-params/src/inject-query-params.spec.ts
- libs/ngxtension/inject-query-params/src/inject-query-params.ts
- libs/ngxtension/inject-route-data/src/inject-route-data.spec.ts
- libs/ngxtension/inject-route-data/src/inject-route-data.ts
- libs/ngxtension/inject-route-fragment/src/inject-route-fragment.spec.ts
- libs/ngxtension/inject-route-fragment/src/inject-route-fragment.ts
- libs/ngxtension/shared/README.md
- libs/ngxtension/shared/ng-package.json
- libs/ngxtension/shared/project.json
- libs/ngxtension/shared/src/index.ts
- libs/ngxtension/shared/src/options/default-value.ts
- libs/ngxtension/shared/src/options/index.ts
- libs/ngxtension/shared/src/options/injector.ts
- libs/ngxtension/shared/src/options/parse.ts
- libs/ngxtension/shared/src/options/transform.ts
- tsconfig.base.json
Adds the following options to all utilities and therefore aligns them.
- injectParams
- transform
- defaultValue
- injector
- injectQueryParams
- defaultValue
- injector
- injectQueryParams.array
- defaultValue
- injector
- injectRouteData
- defaultValue
- injector
- injectRouteFragment
- defaultValue
I also took the chance to rename `initialValue` to `defaultValue` (as I think it's a more fitting name).
`injectQueryParams` supports both values, as to not introduce a breaking change.
> Enhance inject route utilities

- docs/src/content/contributors/pawel-ostromecki.json
Added missing entry in contributors so astro is able to render host binding docs correctly
> docs: Add missing entry in contributors

- docs/src/content/docs/utilities/Operators/take-latest-from.md
- libs/ngxtension/take-latest-from/README.md
- libs/ngxtension/take-latest-from/ng-package.json
- libs/ngxtension/take-latest-from/project.json
- libs/ngxtension/take-latest-from/src/index.ts
- libs/ngxtension/take-latest-from/src/take-latest-from.spec.ts
- libs/ngxtension/take-latest-from/src/take-latest-from.ts
`takeLatestFrom()` is a modification of `withLatestFrom()` operator.
Every time the source observable emits, `takeLatestFrom()` waits for the provided observables to emit a value, and when each of them has emitted, `takeLatestFrom()` emits and unsubscribes from the provided observables.
Let's say we have a source observable `src$` and a provided observable `data$`.
```ts
src$.pipe(
whitLatestFrom(data$)
).subscribe();
```
Cases when `withLatestFrom()` will not emit when `src$` emits:
- if `data$` is a cold observable and emitted before `src$` emitted;
- if `data$` emitted after `src$` emitted (`data$` can be hot or cold).
In the first case, `withLatestFrom()` will wait for the next `data$` value to emit, and `takeLatestFrom()` will do the same.
In the second case, `withLatestFrom()` will …
> feat: introduce takeLatestFrom()

- libs/ngxtension/form-events/src/form-events.spec.ts
- libs/ngxtension/form-events/src/form-events.ts
In all my efforts to get this util all together, I overlooked one of the most important things when it comes to getting form values from reactive forms (for what I argue in the issue is what most people want): getting the value of the form and each control even if the form is disabled.
Closes #491: "Handle getting value from disabled form controls in `form-events` util"
- naming of `form-events` and its functions is outstanding.
- Two existing tests were misphrased and one was not accounting for both of the utils. I threw in changes to those since I was in the test suite anyways.
- @eneajaho about our conversation on naming the signal util: thoughts on `toFormState`? I feel like it is the compliment to the proposed observable util name of `fromFormEvents`.
> refactor: Handle getting value from disabled form controls in `form-events` util

- README.md
- docs/src/content/docs/es/getting-started/installation.mdx
- docs/src/content/docs/es/utilities/Migrations/inject-migration.md
- docs/src/content/docs/getting-started/installation.mdx
- docs/src/content/docs/utilities/Migrations/host-binding-migration.md
- docs/src/content/docs/utilities/Migrations/inject-migration.md
- docs/src/content/docs/utilities/Migrations/new-outputs-migration.md
- docs/src/content/docs/utilities/Migrations/queries-migration.md
- docs/src/content/docs/utilities/Migrations/self-closing-tags.md
- docs/src/content/docs/utilities/Migrations/sfc-migration.md
- docs/src/content/docs/utilities/Migrations/signal-inputs-migration.md
- libs/ngxtension/README.md
- libs/ngxtension/ng-package.json
- libs/ngxtension/package.json
- libs/plugin/generators.json
- libs/plugin/package.json
- libs/plugin/project.json
- libs/plugin/src/generators/init/generator.ts
- nx.json
This publishes `ngxtension-plugin` as an npm package separately.
Closes #410
BREAKING CHANGE:
`ngxtension` no longer contains the generators/schematics.
- If you set up scripts / commands that use `ngxtension` generators/schematics, please install `ngxtension-plugin` under `devDependencies` and use `ngxtension-plugin` generators/schematics instead.
- If you use `initGenerator` programmatically from `ngxtension`, please update your import to `ngxtension-plugin`
> feat: publish ngxtension-plugin separately

- docs/src/content/docs/utilities/Migrations/sfc-migration.md
Updated the sfc-migration documentation according to that issue #549:
Now there is the flag `--move-styles` mentioned
> Updated sfc-migration documentation with adding missed parameters

- libs/ngxtension/inject-local-storage/src/inject-local-storage.spec.ts
- libs/ngxtension/inject-local-storage/src/inject-local-storage.ts
Currently there is no possibility to use `injectLocalStorage` on platform level injection context, without specify explicit providers at the platform.
And there is no possibility to provide specified `NGXTENSION_LOCAL_STORAGE` at the platform level to every application instances on the page, because `NGXTENSION_LOCAL_STORAGE` has `providedIn: root`, and if we inject this token, it overrides `NGXTENSION_LOCAL_STORAGE` from the platform.
> feat(inject-local-storage): promote NGXTENSION_LOCAL_STORAGE token to platform level

- docs/src/content/docs/utilities/Operators/create-repeat.md
When browsing the library's documentation, I often find myself missing something: a native/non-library code example alongside the code that uses the library. This would help demonstrate the actual benefits each utility brings.
As an example, I've added the equivalent RxJS native code implementation next to the create-repeat code example.
Would you be interested in having more such before/after code comparisons in the documentation? If so, I'd be happy to create more examples for other utilities.
If you like the idea but would prefer a different approach, please let me know!
> doc: create repeat, added the nonlibrary code equivalent

- libs/ngxtension/control-value-accessor/src/control-value-accessor.spec.ts
- libs/ngxtension/control-value-accessor/src/control-value-accessor.ts
rxEffect was just used in order to 'escape' setting signals in an effect back then when it was not allowed... this can be done now anyways and could have been done back then aswell, but I did not know at that time about the usage of a normal effect and untracked.
wait for #555
> refactor(ngx-control-value-accessor): use normal effect instead of rxEffect
