- libs/ngxtension/connect/README.md
- libs/ngxtension/connect/ng-package.json
- libs/ngxtension/connect/src/connect.spec.ts
- libs/ngxtension/connect/src/connect.ts
- libs/ngxtension/connect/src/index.ts
- libs/ngxtension/project.json
- tsconfig.base.json
> feat: added connect util fn

- CONTRIBUTING.md
> docs(repo): add CONTRIBUTING guide

- README.md
- docs/astro.config.mjs
- docs/src/content/docs/utilities/create-effect.md
- libs/local-plugin/.eslintrc.json
- libs/local-plugin/generators.json
- libs/local-plugin/src/generators/entry-point/generator.spec.ts
- libs/local-plugin/src/generators/entry-point/generator.ts
- libs/local-plugin/src/generators/entry-point/schema.json
- libs/local-plugin/src/index.ts
- libs/ngxtension/assert-injector/project.json
- libs/ngxtension/computed-from/project.json
- libs/ngxtension/connect/project.json
- libs/ngxtension/create-effect/README.md
- libs/ngxtension/create-effect/ng-package.json
- libs/ngxtension/create-effect/project.json
- libs/ngxtension/create-effect/src/create-effect.spec.ts
- libs/ngxtension/create-effect/src/create-effect.ts
- libs/ngxtension/create-effect/src/index.ts
- libs/ngxtension/create-injection-token/project.json
- libs/ngxtension/repeat/project.json
- libs/ngxtension/resize/project.json
- tsconfig.base.json
> feat(create-effect): add createEffect

- apps/test-app-e2e/src/e2e/if-validator.cy.ts
- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/if-validator/if-validator.component.ts
- docs/astro.config.mjs
- docs/src/content/docs/utilities/if-validator.md
- libs/ngxtension/if-validator/ng-package.json
- libs/ngxtension/if-validator/project.json
- libs/ngxtension/if-validator/src/if-validator.ts
- libs/ngxtension/if-validator/src/index.ts
- tsconfig.base.json
Hi, `ifValidator` or `ifAsyncValidator` are simple utility functions for help to simplify change dynamically validation of Angular Reactive Form.
> feat(): add if-validator

- README.md
- docs/astro.config.mjs
- docs/src/content/docs/utilities/navigation-end.md
- libs/ngxtension/navigation-end/README.md
- libs/ngxtension/navigation-end/ng-package.json
- libs/ngxtension/navigation-end/project.json
- libs/ngxtension/navigation-end/src/index.ts
- libs/ngxtension/navigation-end/src/navigation-end.spec.ts
- libs/ngxtension/navigation-end/src/navigation-end.ts
- tsconfig.base.json
> feat(navigation-end): add navigationEnd util function

- README.md
- apps/test-app-e2e/src/e2e/track-by.cy.ts
- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/track-by/track-by.component.ts
- docs/astro.config.mjs
- docs/src/content/docs/utilities/call-apply.md
- docs/src/content/docs/utilities/trackby-id-prop.md
- libs/ngxtension/trackby-id-prop/README.md
- libs/ngxtension/trackby-id-prop/ng-package.json
- libs/ngxtension/trackby-id-prop/project.json
- libs/ngxtension/trackby-id-prop/src/index.ts
- libs/ngxtension/trackby-id-prop/src/trackby-id-prop.spec.ts
- libs/ngxtension/trackby-id-prop/src/trackby-id-prop.ts
- package.json
- pnpm-lock.yaml
- tsconfig.base.json
I've implemented the `trackById` and `trackByProp` directives as discussed in #33 
+ added some tests (but don't found a way to verify the real implementation detail of trackBy)
+ added docs to astro + updated the main README to add the missing link to utilities: call-apply and this new ones
> feat(track-id-prop): add trackById and trackByProp directives #33

- README.md
- docs/astro.config.mjs
**Changes:**
* Readme - sort utilities alphabetically
* astro.config.mjs - sort items alphabetically
**Releated Issue:**
closes #60 
**Note** -
The astro part can be done via sort() function, however since the reamde should be maintined manually anyone, i think its better to leave the astro sorted manually as well.
> Docs - Sort utilities alphabetically

- docs/src/content/docs/utilities/filter-array.md
- docs/src/content/docs/utilities/filter-nil.md
- docs/src/content/docs/utilities/map-array.md
- libs/ngxtension/filter-array/README.md
- libs/ngxtension/filter-array/ng-package.json
- libs/ngxtension/filter-array/project.json
- libs/ngxtension/filter-array/src/filter-array.spec.ts
- libs/ngxtension/filter-array/src/filter-array.ts
- libs/ngxtension/filter-array/src/index.ts
- libs/ngxtension/filter-nil/README.md
- libs/ngxtension/filter-nil/ng-package.json
- libs/ngxtension/filter-nil/project.json
- libs/ngxtension/filter-nil/src/index.ts
- libs/ngxtension/filter-nil/src/map-array.spec.ts
- libs/ngxtension/filter-nil/src/map-array.ts
- libs/ngxtension/map-array/README.md
- libs/ngxtension/map-array/ng-package.json
- libs/ngxtension/map-array/project.json
- libs/ngxtension/map-array/src/index.ts
- libs/ngxtension/map-array/src/map-array.spec.ts
- libs/ngxtension/map-array/src/map-array.ts
- tsconfig.base.json
> feat(rxjs): create a set of rxjs operators

- docs/src/content/docs/utilities/reduce-array.md
- libs/ngxtension/reduce-array/README.md
- libs/ngxtension/reduce-array/ng-package.json
- libs/ngxtension/reduce-array/project.json
- libs/ngxtension/reduce-array/src/index.ts
- libs/ngxtension/reduce-array/src/reduce-array.spec.ts
- libs/ngxtension/reduce-array/src/reduce-array.ts
same as `mapArray` but for `.reduce()` function
> added reduce-array operator

- apps/test-app-e2e/src/e2e/drag.cy.ts
- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/drag/drag.component.ts
- apps/test-app/src/styles.css
- docs/src/content/docs/utilities/Gesture/drag.mdx
- docs/src/content/docs/utilities/Gesture/intro.md
- libs/ngxtension/.eslintrc.json
- libs/ngxtension/gestures/README.md
- libs/ngxtension/gestures/ng-package.json
- libs/ngxtension/gestures/project.json
- libs/ngxtension/gestures/src/drag.ts
- libs/ngxtension/gestures/src/index.ts
- libs/ngxtension/gestures/src/zoneless-gesture.ts
- libs/ngxtension/package.json
- package.json
- pnpm-lock.yaml
- tsconfig.base.json
> feat(gestures): port Drag Gesture from use-gesture

- docs/src/content/docs/utilities/Injectors/create-injection-token.md
- libs/ngxtension/create-injection-token/src/create-injection-token.spec.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
> fix(create-injection-token): allows multi token to work correctly

- libs/ngxtension/create-injection-token/src/create-injection-token.spec.ts
- libs/ngxtension/create-injection-token/src/create-injection-token.ts
Closes #99
No docs yet because my brain is not firing on all cylinders this morning (Insomnia struck last night so I've been up since 2AM). I'll add docs later or @wanoo21 can put some docs 😋. 
cc @wanoo21 no docs so you might want to take a look at the new tests in this PR for usage.
For "optional factory" case, I had to add a new function `createNoopInjectionToken()` instead. Typing is tricky with the optional factory.
```ts
// "multi" token; unfortunately until I can acquire better typescript skill, we have to duplicate "true" here
const [injectFn, provideFn] = createNoopInjectionToken<number, true>('description', { multi: true });
injectFn(); // number[]
provideFn(1); // accepts number
provideFn(() => 1); // accepts a factory returning a number
// normal token
const [injectFn, …
```
> fix(create-injection-token): allow provideFn to accept factory

- libs/ngxtension/computed-from/src/computed-from.spec.ts
Hi @eneajaho , before proceeding with #37 (if we'll agree to the desired final feature)
I added some tests to `computedFrom` to verify current "tricky" behavior that you documented in docs, so I can use them to verify my new implementation and try to fix some of them, without undesired breaking change where possible!
> fix(computedFrom) add tricky tests

- docs/src/content/docs/utilities/Operators/debug.md
- libs/ngxtension/debug/README.md
- libs/ngxtension/debug/ng-package.json
- libs/ngxtension/debug/project.json
- libs/ngxtension/debug/src/debug.spec.ts
- libs/ngxtension/debug/src/debug.ts
- libs/ngxtension/debug/src/index.ts
- tsconfig.base.json
Add RxJs operator debug (to output on console all events of an Observable pipeline) as proposed in #34 + related docs (hope in the right place 😉 )
> feat (debug) add rxjs operator debug + docs

- docs/src/content/docs/utilities/Injectors/create-injection-token.md
I tried to include everything I remember about the new updates of `createInjectionToken` and `createNoopInjectionToken`. If there's anything I missed, please let me know.
Also, a few examples were taken from tests and the docs are based on source code.
@nartc would be good if you'd check the examples, to ensure I haven't forgotten anything.
> docs: update create injection token

- libs/ngxtension/src/test-setup.ts
- package.json
- pnpm-lock.yaml
add observer spy to dev dependancy to test observables
> feat(test): add observer-spy

- docs/src/content/docs/utilities/Injectors/inject-is-intersecting.md
- libs/ngxtension/inject-is-intersecting/README.md
- libs/ngxtension/inject-is-intersecting/ng-package.json
- libs/ngxtension/inject-is-intersecting/project.json
- libs/ngxtension/inject-is-intersecting/src/index.ts
- libs/ngxtension/inject-is-intersecting/src/inject-is-intersecting.spec.ts
- libs/ngxtension/inject-is-intersecting/src/inject-is-intersecting.ts
- libs/ngxtension/inject-is-intersecting/src/is-in-viewport.service.ts
- tsconfig.base.json
> feat: added inject-is-intersecting

- README.md
> docs: added the logo

- docs/src/content/docs/utilities/Injectors/inject-params.md
- docs/src/content/docs/utilities/Injectors/inject-query-params.md
- libs/ngxtension/inject-params/README.md
- libs/ngxtension/inject-params/ng-package.json
- libs/ngxtension/inject-params/project.json
- libs/ngxtension/inject-params/src/index.ts
- libs/ngxtension/inject-params/src/inject-params.spec.ts
- libs/ngxtension/inject-params/src/inject-params.ts
- libs/ngxtension/inject-query-params/README.md
- libs/ngxtension/inject-query-params/ng-package.json
- libs/ngxtension/inject-query-params/project.json
- libs/ngxtension/inject-query-params/src/index.ts
- libs/ngxtension/inject-query-params/src/inject-query-params.spec.ts
- libs/ngxtension/inject-query-params/src/inject-query-params.ts
- tsconfig.base.json
https://twitter.com/Enea_Jahollari/status/1720078134719152200 this tweet but better and with tests 😄
close #137
> feat: added inject params and inject query params

- docs/src/content/docs/utilities/Operators/rx-effect.md
- libs/ngxtension/rx-effect/README.md
- libs/ngxtension/rx-effect/ng-package.json
- libs/ngxtension/rx-effect/project.json
- libs/ngxtension/rx-effect/src/index.ts
- libs/ngxtension/rx-effect/src/rx-effect.spec.ts
- libs/ngxtension/rx-effect/src/rx-effect.ts
- tsconfig.base.json
implement the #151 feature request
> #151 feat(rx-effect): implement the function to handle rxjs effects

- libs/ngxtension/create-injection-token/src/create-injection-token.ts
> fix(create-injection-token): better decide when to use factory or provided value (#161)

- docs/astro.config.mjs
- docs/src/components/Content.astro
- docs/src/components/PageTitle.astro
- docs/src/content/config.ts
- docs/src/content/docs/utilities/Operators/filter-array.md
- docs/src/content/docs/utilities/Operators/filter-nil.md
- docs/src/content/docs/utilities/Operators/map-array.md
> feat: add contributors and badge to doc pages

- docs/src/content/docs/utilities/Injectors/inject-network.md
- libs/ngxtension/inject-network/README.md
- libs/ngxtension/inject-network/ng-package.json
- libs/ngxtension/inject-network/project.json
- libs/ngxtension/inject-network/src/index.ts
- libs/ngxtension/inject-network/src/inject-network.spec.ts
- libs/ngxtension/inject-network/src/inject-network.ts
- tsconfig.base.json
Ported from https://vueuse.org/core/useNetwork
> feat: ported injectNetwork() to Angular

- README.md
Just doing my part for those sweet contribution credits ;)
> docs: update readme to point to angular.dev

- libs/ngxtension/connect/src/connect.spec.ts
- libs/ngxtension/connect/src/connect.ts
Closes https://github.com/nartc/ngxtension-platform/issues/208
> feat: connect two signals with each other

- docs/src/content/docs/utilities/Migrations/signal-inputs-migration.md
> docs: add docs for signal inputs migration

- docs/src/content/docs/es/utilities/Forms/control-value-accessor.md
- docs/src/content/docs/utilities/Forms/control-value-accessor.md
Adds an import section in the docs.
> docs(NgxControlValueAccessor): add import section

- libs/ngxtension/computed-async/src/computed-async.spec.ts
- libs/ngxtension/computed-async/src/computed-async.ts
> feat: add requireSync to computedAsync for better typings

- libs/ngxtension/computed-async/src/computed-async.spec.ts
- libs/ngxtension/computed-async/src/computed-async.ts
By moving the subscription above the effect, we could remove some code duplication. And instead of skipping the observable, we know just skip using a flag inside the effect.
> fix: contextual observables + requireSync

- docs/src/content/docs/utilities/Signals/merge-from.md
- libs/ngxtension/merge-from/README.md
- libs/ngxtension/merge-from/ng-package.json
- libs/ngxtension/merge-from/project.json
- libs/ngxtension/merge-from/src/lib/merge-from.spec.ts
- libs/ngxtension/merge-from/src/lib/merge-from.ts
- tsconfig.base.json
> feat(merge-from): add mergeFrom

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
> fix(convert-signal-inputs): remove unnecessary undefined

- docs/src/content/docs/utilities/Signals/merge-from.md
> docs(merge-from): add documentation for mergeFrom

- docs/src/content/contributors/evgeniy-oz.json
Links to my twitter, github, medium
> docs: add links to e-oz profile

- libs/ngxtension/if-validator/src/if-validator.spec.ts
- libs/ngxtension/if-validator/src/if-validator.ts
> fix(if-validator): exclude individual validators from composition to allow presence checks

- docs/astro.config.mjs
- docs/package.json
- docs/pnpm-lock.yaml
- docs/src/components/Sidebar.astro
> docs: remember sidebar scroll state

- libs/plugin/generators.json
- libs/plugin/src/generators/convert-outputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-outputs/compat.ts
- libs/plugin/src/generators/convert-outputs/generator.spec.ts
- libs/plugin/src/generators/convert-outputs/generator.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
fixes https://github.com/nartc/ngxtension-platform/issues/310
> fix: fix output migrations issue

- README.md
Feel free to dismiss if this isn't wanted. :)
> docs: add npm downloads and version badges to README.md

- docs/src/components/PageTitle.astro
Example:
Resolves to: https://github.com/nartc/ngxtension-platform/tree/main/libs/ngxtension/connect
Feel free to dismiss :)
> docs: add a code to source code button

- docs/src/content/docs/getting-started/installation.mdx
> docs: add bun add command to install section

- docs/src/content/docs/utilities/Migrations/inject-migration-migration.md
- libs/plugin/src/generators/convert-di-to-inject/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-di-to-inject/generator.spec.ts
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.d.ts
- libs/plugin/src/generators/convert-di-to-inject/schema.json
It supports everything 🎉
Before: 
After: 
Also inspiration taken from: https://github.com/kreuzerk/inject-pilot/tree/main 
cc @kreuzerk @ilirbeqirii
> feat: added inject migration

- docs/src/content/docs/utilities/Gesture/gesture.mdx
- libs/ngxtension/package.json
Closes https://github.com/ngxtension/ngxtension-platform/issues/348
> fix: make @use-gesture/vanilla optional dependency

- docs/package.json
- docs/pnpm-lock.yaml
- docs/src/content/docs/utilities/Migrations/queries-migration.md
> docs: convert queries

- libs/plugin/src/generators/convert-di-to-inject/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
> fix(plugin): add and remove this keyword correctly

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
> fix(plugin): add string to input generic

- docs/src/content/docs/utilities/Migrations/inject-migration.md
I wanted to update the inject migration docs, but I noticed you already did this within #340 ~ thank you!
However, I added a missing `inject` import 😉
> docs: update inject migration example

- docs/src/content/docs/es/utilities/Operators/filter-array.md
- docs/src/content/docs/es/utilities/Operators/filter-nil.md
- docs/src/content/docs/es/utilities/Operators/map-array.md
Spanish translations for: 
* operators/filter-array
* operators/filterNil
* operators/map-array
> Spanish translations for a few operators 

- libs/plugin/src/generators/convert-di-to-inject/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-di-to-inject/generator.spec.ts
- libs/plugin/src/generators/convert-di-to-inject/generator.ts
Closes #443 
To be honest, I don't khow exactly how this fixes the migration, but it works 😅
> fix(plugin): update all assignments

- libs/plugin/src/generators/convert-signal-inputs/__snapshots__/generator.spec.ts.snap
- libs/plugin/src/generators/convert-signal-inputs/generator.spec.ts
- libs/plugin/src/generators/convert-signal-inputs/generator.ts
> fix(signal-input-migration): skip inputs with @HostBinding() decorator

- libs/ngxtension/signal-slice/src/signal-slice.ts
@dirkluijk fix proposal for action streams infered as never
> fix(signal-slice): fix action streams being infered as never

- docs/src/content/docs/utilities/Injectors/inject-local-storage.md
Added docs for injectLocalStorage #464
> docs: Added docs for injectLocalStorage

- docs/src/content/docs/utilities/Injectors/inject-query-params.md
Just added some more info on how to remove duplicated code when it comes to query params
> chore(docs): add docs on how to reduce code duplication

- libs/ngxtension/control-value-accessor/src/control-value-accessor.ts
> feat(ngx-control-value-accessor): expose the NgControl instance of the host

- libs/ngxtension/inject-local-storage/src/inject-local-storage.spec.ts
- libs/ngxtension/inject-local-storage/src/inject-local-storage.ts
> feat(inject-local-storage): dispatch storage event on change (#523)

- libs/ngxtension/linked-query-param/src/linked-query-param.ts
Fixes https://github.com/ngxtension/ngxtension-platform/issues/539
> fix: add preserveFragment to linkedQueryParam navigation extras

- apps/test-app/src/app/app.component.ts
- apps/test-app/src/app/app.config.ts
- apps/test-app/src/app/signal-history/signal-history.component.ts
- docs/src/content/docs/utilities/Injectors/signal-history.md
- libs/ngxtension/signal-history/README.md
- libs/ngxtension/signal-history/ng-package.json
- libs/ngxtension/signal-history/project.json
- libs/ngxtension/signal-history/src/index.ts
- libs/ngxtension/signal-history/src/signal-history.spec.ts
- libs/ngxtension/signal-history/src/signal-history.ts
- tsconfig.base.json
Useful when you need to implement undo/redo functionality on your app
https://github.com/user-attachments/assets/f181353c-a8ff-45f6-a7e3-58e037a642ed
Inspired from https://vueuse.org/core/useRefHistory/
> feat: add injectSignalHistory implementation, tests and docs

- libs/ngxtension/singleton-proxy/src/singleton-proxy.spec.ts
> test: added tests for singleton-proxy

- docs/src/content/docs/utilities/Forms/form-events.md
Added missings docs for `form-events` utility functions
> docs: form-events

- libs/ngxtension/form-events/src/form-events.spec.ts
- libs/ngxtension/form-events/src/form-events.ts
> feat(form-events): provide optional injector for both form event utils

- libs/ngxtension/computed-previous/src/computed-previous.spec.ts
- libs/ngxtension/computed-previous/src/computed-previous.ts
> feat(computed-previous): lazy computed previous (#590)

- docs/src/content/docs/utilities/Injectors/inject-local-storage.md
- libs/ngxtension/inject-local-storage/src/inject-local-storage.spec.ts
- libs/ngxtension/inject-local-storage/src/inject-local-storage.ts
- libs/ngxtension/src/test-setup.ts
> feat(inject-local-storage): computed key support (#569)

- libs/ngxtension/host-binding/src/host-binding.spec.ts
- libs/ngxtension/host-binding/src/host-binding.ts
> fix(host-binding): allow to bind the style property with an object to set multiple CSS properties (including variables) at once
